-- 프로그래머스 131118 서울에 위치한 식당 목록 출력하기
SELECT 
    DISTINCT I.REST_ID, 
    I.REST_NAME, 
    I.FOOD_TYPE, 
    I.FAVORITES, 
    I.ADDRESS, 
    ROUND(AVG(REVIEW_SCORE) OVER (PARTITION BY R.REST_ID), 2) AS SCORE
FROM REST_INFO I INNER JOIN REST_REVIEW R ON I.REST_ID=R.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;