-- 프로그래머스 59413 입양 시각 구하기(2)

-- 0시 ~ 23시 테이블 (HOURS) 생성
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

-- LEFT JOIN 으로 처리

SELECT H.HOUR, IFNULL(O.COUNT, 0) AS COUNT
FROM HOURS H
    LEFT JOIN (
        SELECT HOUR(DATETIME) AS HR, COUNT(*) AS COUNT
        FROM ANIMAL_OUTS
        GROUP BY HR
        ) O
    ON H.HOUR=O.HR
ORDER BY HOUR ASC;