-- 프로그래머스 133027 주문량이 많은 아이스크림들 조회하기
SELECT DISTINCT FH.FLAVOR
FROM FIRST_HALF FH INNER JOIN JULY JUL ON FH.FLAVOR=JUL.FLAVOR
ORDER BY FH.TOTAL_ORDER + SUM(JUL.TOTAL_ORDER) OVER (PARTITION BY JUL.FLAVOR) DESC LIMIT 3;