-- 프로그래머스 157342 자동차 평균 대여 기간 구하기
SELECT 
    CAR_ID,
    ROUND(SUM((DATEDIFF(END_DATE, START_DATE)+1))/COUNT(CAR_ID), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
    HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

-- mysql에 AVERAGE()라는 함수는 없다
-- 평균을 구하고 싶으면 AVG()를 써야함 