-- 프로그래머스 164673 조건에 부합하는 중고거래 댓글 조회하기
-- USED_GOODS_BOARD, USED_GOODS_REPLY
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY R
    INNER JOIN USED_GOODS_BOARD B ON R.BOARD_ID=B.BOARD_ID
WHERE B.CREATED_DATE like '2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;