-- 프로그래머스 131532 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE S INNER JOIN USER_INFO U ON S.USER_ID=U.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;