-- 프로그래머스 164668 조건에 맞는 사용자와 총 거래금액 조회하기
SELECT *
FROM (
    SELECT U.USER_ID, U.NICKNAME, SUM(G.PRICE) OVER (PARTITION BY G.WRITER_ID) AS TOTAL_SALES
    FROM USED_GOODS_BOARD G INNER JOIN USED_GOODS_USER U ON G.WRITER_ID=U.USER_ID
    WHERE G.STATUS='DONE'
    ) A
WHERE TOTAL_SALES >= 700000
GROUP BY USER_ID
ORDER BY TOTAL_SALES;