-- 프로그래머스 164671 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기

-- group function error 발생

-- SELECT B.BOARD_ID, F.FILE_ID, F.FILE_NAME, F.FILE_EXT
-- FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID=F.BOARD_ID
-- WHERE B.VIEWS=MAX(B.VIEWS)
-- ORDER BY F.FILE_ID DESC;

SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID=F.BOARD_ID
WHERE B.VIEWS=(SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;

SELECT B.BOARD_ID, B.VIEWS
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID=F.BOARD_ID
ORDER BY B.VIEWS DESC, F.FILE_ID DESC;
