-- 프로그래머스 144856 저자 별 카테고리 별 매출액 집계하기
-- 성공
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES 
FROM BOOK_SALES BS
    INNER JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

-- 실패
WITH BOOK_INFO AS (
    SELECT distinct B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, BS.SALES_DATE, SUM(BS.SALES) OVER (PARTITION BY B.BOOK_ID) AS CNT
    FROM BOOK B INNER JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE SALES_DATE LIKE '2022-01-%'
)
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.CNT * B.PRICE AS TOTAL_SALES 
FROM BOOK_INFO B INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

-- 성공 sql문과 실패 sql이 일부는 결과가 같고 일부는 다르다! 이유는 모르겠다! 